using System;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Xml;

namespace ArcCore.UI
{
    // Simple exporter: converts the internal JSON DTO (nodes[], edges[]) into DOT, Mermaid or DGML.
    public static class GraphExporter
    {
        public static string ToDot(string graphJson)
        {
            using var doc = JsonDocument.Parse(graphJson);
            var sb = new StringBuilder();
            sb.AppendLine("// Generated by ArcGraph exporter (DOT)");
            sb.AppendLine("digraph G {");
            sb.AppendLine("  rankdir=LR;");
            sb.AppendLine("  node [shape=circle, style=filled, fontsize=10];");

            if (doc.RootElement.TryGetProperty("nodes", out var nodes))
            {
                foreach (var n in nodes.EnumerateArray())
                {
                    var id = SafeId(n.GetProperty("id").GetString() ?? "");
                    var label = (n.TryGetProperty("label", out var lab) ? lab.GetString() : id) ?? id;
                    var fill = n.TryGetProperty("backgroundColor", out var bg) ? bg.GetString() : null;
                    var attrs = new StringBuilder();
                    attrs.Append($"label=\"{Escape(label)}\"");
                    if (!string.IsNullOrEmpty(fill)) attrs.Append($", fillcolor=\"{fill}\"");
                    sb.AppendLine($"  \"{id}\" [{attrs}];");
                }
            }

            if (doc.RootElement.TryGetProperty("edges", out var edges))
            {
                foreach (var e in edges.EnumerateArray())
                {
                    var s = SafeId(e.GetProperty("source").GetString() ?? "");
                    var t = SafeId(e.GetProperty("target").GetString() ?? "");
                    var weight = e.TryGetProperty("weight", out var w) ? w.GetRawText() : "1";
                    var isViolation = e.TryGetProperty("isViolation", out var v) && v.GetBoolean();
                    var color = isViolation ? "#d9534f" : "#999";
                    sb.AppendLine($"  \"{s}\" -> \"{t}\" [penwidth={Math.Max(1, Math.Min(6, int.TryParse(weight, out var wi) ? wi : 1))}, color=\"{color}\"];");
                }
            }

            sb.AppendLine("}");
            return sb.ToString();
        }

        public static string ToMermaid(string graphJson)
        {
            using var doc = JsonDocument.Parse(graphJson);
            var sb = new StringBuilder();
            sb.AppendLine("%% Generated by ArcGraph exporter (Mermaid)");
            sb.AppendLine("graph LR");

            if (doc.RootElement.TryGetProperty("nodes", out var nodes))
            {
                foreach (var n in nodes.EnumerateArray())
                {
                    var id = SafeId(n.GetProperty("id").GetString() ?? "");
                    var label = (n.TryGetProperty("label", out var lab) ? lab.GetString() : id) ?? id;
                    sb.AppendLine($"  {id}[\"{Escape(label)}\"]");
                }
            }

            if (doc.RootElement.TryGetProperty("edges", out var edges))
            {
                foreach (var e in edges.EnumerateArray())
                {
                    var s = SafeId(e.GetProperty("source").GetString() ?? "");
                    var t = SafeId(e.GetProperty("target").GetString() ?? "");
                    var isViolation = e.TryGetProperty("isViolation", out var v) && v.GetBoolean();
                    var style = isViolation ? ":::violation" : "";
                    sb.AppendLine($"  {s} --> {t} {style}");
                }
            }

            // optional: define class style for violation
            sb.AppendLine("classDef violation stroke:#d9534f,stroke-width:2px;");
            return sb.ToString();
        }

        public static string ToDgml(string graphJson)
        {
            using var doc = JsonDocument.Parse(graphJson);
            var settings = new XmlWriterSettings { Indent = true, Encoding = Encoding.UTF8 };
            var sb = new StringBuilder();
            using var xw = XmlWriter.Create(sb, settings);
            xw.WriteStartDocument();
            xw.WriteStartElement("DirectedGraph", "http://schemas.microsoft.com/vs/2009/dgml");

            xw.WriteStartElement("Nodes");
            if (doc.RootElement.TryGetProperty("nodes", out var nodes))
            {
                foreach (var n in nodes.EnumerateArray())
                {
                    var id = n.GetProperty("id").GetString() ?? "";
                    var label = (n.TryGetProperty("label", out var lab) ? lab.GetString() : id) ?? id;
                    var category = n.TryGetProperty("group", out var g) ? g.GetString() : null;
                    xw.WriteStartElement("Node");
                    xw.WriteAttributeString("Id", id);
                    xw.WriteAttributeString("Label", label);
                    if (!string.IsNullOrEmpty(category)) xw.WriteAttributeString("Category", category);
                    xw.WriteEndElement();
                }
            }
            xw.WriteEndElement(); // Nodes

            xw.WriteStartElement("Links");
            if (doc.RootElement.TryGetProperty("edges", out var edges))
            {
                foreach (var e in edges.EnumerateArray())
                {
                    var s = e.GetProperty("source").GetString() ?? "";
                    var t = e.GetProperty("target").GetString() ?? "";
                    var isViolation = e.TryGetProperty("isViolation", out var v) && v.GetBoolean();
                    xw.WriteStartElement("Link");
                    xw.WriteAttributeString("Source", s);
                    xw.WriteAttributeString("Target", t);
                    if (isViolation) xw.WriteAttributeString("Category", "Violation");
                    xw.WriteEndElement();
                }
            }
            xw.WriteEndElement(); // Links

            // Optional categories
            xw.WriteStartElement("Categories");
            xw.WriteStartElement("Category");
            xw.WriteAttributeString("Id", "Violation");
            xw.WriteAttributeString("Label", "Violation");
            xw.WriteEndElement();
            xw.WriteEndElement();

            xw.WriteEndElement(); // DirectedGraph
            xw.WriteEndDocument();
            xw.Flush();
            return sb.ToString();
        }

        private static string Escape(string s)
        {
            return s?.Replace("\"", "\\\"") ?? "";
        }

        // DOT identifiers: make them safe (but keep original mapping simpler by quoting)
        private static string SafeId(string id)
        {
            // keep as-is — will be quoted when used
            return id;
        }
    }
}